imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
podSecurityContext:
  fsGroup: 1000
archivebox:
  superUser:
    userName: myuser
    userEmail: myuser@test.com
    userPassword: mypass
  storage:
    archive:
      storageClassName: default
      size: 20G
    temp:
      storageClassName: default
      size: 5G
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  image:
    repository: ghcr.io/iloveyatoo/archivebox
    pullPolicy: Always
    tag: ""
  securityContext:
    capabilities:
      drop:
      - ALL
    runAsUser: 1000
    runAsGroup: 1000
    readOnlyRootFilesystem: true

nginx:
  storage:
    nginx:
      storageClassName: default
      size: 1G
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  image:
    repository: nginxinc/nginx-unprivileged
    pullPolicy: Always
    tag: ""
  securityContext:
    capabilities:
      drop:
      - ALL
    runAsUser: 101
    runAsGroup: 101
    readOnlyRootFilesystem: true