--- 
jobs:
  helm-build-stable: 
    machine: 
      docker_layer_caching: true
      image: "ubuntu-2004:2022.04.1"
      resource_class: medium
    steps: 
      - 
        checkout: 
          path: ~/app
      -
        run:
          command: |
            pip3 install yq
          name: Install Dependencies
      - 
        run: 
          command: |
            export CHART_NAME=$(yq -r .name Chart.yaml)
            export CHART_VERSION=$(yq -r .version Chart.yaml)
            export CHART_TGZ="$CHART_NAME-$CHART_VERSION.tgz"
            if [[ $(curl --request GET --url https://storage.bunnycdn.com/iloveyatoo-helm/ --header 'Accept: */*' --header "AccessKey: $BUNNY_STORAGE_HELM_KEY" | jq -r '.[] | select(.ObjectName==env.CHART_TGZ)') ]]
            then
              helm package ~/app
              mkdir target
              mv $CHART_TGZ target/
              helm repo index target --url https://helm.iloveyatoo.net
              ls 
              ls target
            fi
          name: "Build Helm Chart"
    working_directory: ~/app
version: 2.1
workflows: 
  default: 
    jobs: 
      - helm-build-stable:
          filters:
            branches:
              only: master
          context: 
            - bunny-storage-helm