---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "archivebox.fullname" . }}-nginx-conf
  labels:
    {{- include "archivebox.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections  1024;
    }
    http {
      server {
          listen 8080;
          server_name _;
          location / {
            proxy_pass http://{{ .Chart.Name }}:8000/;
            proxy_buffering off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
          }
          location /static {
            root /usr/share/nginx/html/static;
          }
      }
    }
