---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "archivebox.fullname" . }}-nginx-conf
  labels:
    {{- include "archivebox.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen 8080;
      server_name _;
      location / {
        proxy_pass http://127.0.0.1:8000/;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300; 
      }
      location /static/ {
        alias /usr/share/nginx/html/;
      }
    }
