apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "archivebox.fullname" . }}
  labels:
    {{- include "archivebox.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "archivebox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "archivebox.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "archivebox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/app/venv/bin/gunicorn']
          args: 
            - --pythonpath 
            - /app/venv/lib/python3.10/site-packages/archivebox 
            - -b 
            - 0.0.0.0:8000 
            - archivebox.wsgi:application
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "archivebox.fullname" . }}
              mountPath: /app/data
        - name: {{ .Chart.Name }}-nginx
          securityContext:
              runAsUser: 101
              runAsGroup: 101
          image: nginxinc/nginx-unprivileged
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: {{ include "archivebox.fullname" . }}-nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
            - name: {{ include "archivebox.fullname" . }}-nginx
              mountPath: /usr/share/nginx/html
              readOnly: true
      initContainers:
        - name: {{ .Chart.Name }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/app/venv/bin/archivebox']
          args: ['init']
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "archivebox.fullname" . }}
              mountPath: /app/data
        - name: {{ .Chart.Name }}-createuser
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/bin/sh', '/docker/createsuperuser.sh']
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "archivebox.fullname" . }}
              mountPath: /app/data
          env:
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ include "archivebox.fullname" . }}"
                  key: userName
                  optional: false
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: "{{ include "archivebox.fullname" . }}"
                  key: userEmail
                  optional: false
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "archivebox.fullname" . }}"
                  key: userPassword
                  optional: false
        - name: {{ .Chart.Name }}-copystaticfiles
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/bin/sh', '-c', 'archivebox manage collectstatic && cp -R /app/static /nginx/static']
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "archivebox.fullname" . }}-nginx
              mountPath: /nginx
            - name: {{ include "archivebox.fullname" . }}
              mountPath: /app/data
      volumes:
      - name: {{ include "archivebox.fullname" . }}
        persistentVolumeClaim:
          claimName: {{ include "archivebox.fullname" . }}
      - name: {{ include "archivebox.fullname" . }}-nginx
        persistentVolumeClaim:
          claimName: {{ include "archivebox.fullname" . }}-nginx
      - name: {{ include "archivebox.fullname" . }}-nginx-conf
        configMap:
          name: {{ include "archivebox.fullname" . }}-nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
