---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "archivebox.fullname" . }}
  labels:
    {{- include "archivebox.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.archivebox.storage.archive.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.archivebox.storage.archive.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "archivebox.fullname" . }}-nginx
  labels:
    {{- include "archivebox.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.nginx.storage.nginx.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.nginx.storage.nginx.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "archivebox.fullname" . }}-tmp
  labels:
    {{- include "archivebox.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.archivebox.storage.temp.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.archivebox.storage.temp.size }}