apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "archivebox.fullname" . }}
  labels:
    {{- include "archivebox.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}