apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "archivebox.fullname" . }}"
  labels:
    {{- include "archivebox.labels" . | nindent 4 }}
type: Opaque
stringData:
  userName: {{ .Values.archivebox.superUser.userName }}
  userEmail: {{ .Values.archivebox.superUser.userEmail }}
  userPassword: {{ .Values.archivebox.superUser.userPassword }}