apiVersion: v1
kind: Service
metadata:
  name: {{ include "archivebox.fullname" . }}
  labels:
    {{- include "archivebox.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "archivebox.selectorLabels" . | nindent 4 }}
